"""
Unit Test for Skill: target_prioritization
Generated by Skillify on 2026-04-23T09:12:38.608204
"""

import pytest
import sys
sys.path.insert(0, '.')

from script import execute_target_prioritization, validate_output


class TestSkill:
    def test_basic_execution(self):
        """Test basic task execution"""
        params = {"disease": "masld", "query": "MASLD drug targets"}
        result = execute_target_prioritization(params)
        assert result.get("status") == "success", f"Expected success, got: {result}"
    
    def test_output_validation(self):
        """Test output schema validation"""
        params = {"disease": "masld", "query": "MASLD drug targets"}
        result = execute_target_prioritization(params)
        assert validate_output(result), "Output validation failed"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
